name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Project
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Run test
        run: yarn test
        env:
          CI: true